spring.profiles.active=${ACTIVE_PROFILE}

# Spring Application
spring.application.name=rental-profitability

# Server Configuration
server.port=8080
server.servlet.context-path=/

# Jackson JSON Configuration
spring.jackson.default-property-inclusion=NON_NULL
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.deserialization.fail-on-unknown-properties=false

# Management/Actuator Configuration
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=when-authorized

# Database Configuration
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=${DATABASE_DRIVER}

# OpenAI Configuration
openai.api.key=${OPENAI_API_KEY}
openai.api.model=gpt-4-turbo-preview
openai.api.temperature=0.7
openai.api.max-tokens=4095

#BrigthData
brightdata.api.key = ${BRIGHTDATA_API_KEY}
brightdata.dataset.key = ${BRIGHTDATA_DATASET_ID}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Set the path to serve static content from
spring.resources.static-locations=classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/